import type { EstimateFileV1,InvoiceItem,Settings } from './types';
export class EstimateFileError extends Error{constructor(message:string){super(message);this.name='EstimateFileError'}}
export const ESTIMATE_FORMAT_VERSION=1 as const; const SCRIPT_ID='estimate-data';
const esc=(v:string)=>v.replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const safeJson=(v:string)=>v.replaceAll('</script','<\\/script').replaceAll('<!--','<\\!--');
const validItem=(v:unknown):v is InvoiceItem=>{if(!v||typeof v!=='object')return false;const x=v as Record<string,unknown>;return typeof x.id==='string'&&typeof x.name==='string'&&typeof x.description==='string'&&typeof x.quantity==='number'&&Number.isFinite(x.quantity)&&x.quantity>0&&typeof x.priceKopecks==='number'&&Number.isInteger(x.priceKopecks)&&x.priceKopecks>=0&&typeof x.unit==='string'&&(x.type==='service'||x.type==='product')&&typeof x.categoryId==='string'&&(x.catalogId===undefined||typeof x.catalogId==='string')};
const parse=(raw:unknown):EstimateFileV1=>{if(!raw||typeof raw!=='object')throw new EstimateFileError('Неверный формат файла.');const d=raw as Record<string,unknown>;if(d.version!==1||d.app!=='santeh-schet')throw new EstimateFileError(`Неподдерживаемая версия файла: ${String(d.version??'неизвестно')}`);if(!Array.isArray(d.items)||!d.items.every(validItem))throw new EstimateFileError('Список позиций сметы повреждён.');const s=d.settings as Record<string,unknown>|null; if(!s||typeof s.address!=='string')throw new EstimateFileError('Настройки сметы повреждены.');const discount=typeof s.discount==='number'?s.discount:typeof s.discountPercent==='number'?s.discountPercent:0;const settings={address:s.address,discount:Math.max(0,Math.min(50,discount)),discountPercent:Math.max(0,Math.min(50,discount))};return{version:1,app:'santeh-schet',name:typeof d.name==='string'&&d.name?d.name:'Импортированная смета',items:d.items as InvoiceItem[],settings,savedAt:typeof d.savedAt==='number'?d.savedAt:Date.now()};};
export const serializeEstimate=(items:InvoiceItem[],settings:Settings,name:string)=>{const data:EstimateFileV1={version:1,app:'santeh-schet',name,items,settings,savedAt:Date.now()};const rows=items.map((i,n)=>`<tr><td>${n+1}</td><td>${esc(i.name)}</td><td>${esc(String(i.quantity))} ${esc(i.unit)}</td><td>${esc((i.priceKopecks/100).toLocaleString('ru-RU'))} ₽</td></tr>`).join('');return`<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Смета — ${esc(name)}</title><style>body{font:14px system-ui;max-width:900px;margin:40px auto;padding:0 16px}table{width:100%;border-collapse:collapse}th,td{padding:8px;border-bottom:1px solid #ddd;text-align:left}</style></head><body><h1>${esc(name)}</h1><p>${esc(settings.address)}</p><table><thead><tr><th>№</th><th>Наименование</th><th>Кол-во</th><th>Цена</th></tr></thead><tbody>${rows}</tbody></table><script type="application/json" id="${SCRIPT_ID}">${safeJson(JSON.stringify(data))}</script></body></html>`};
export const saveEstimateToFile=(items:InvoiceItem[],settings:Settings,customName?:string)=>{if(!items.length||typeof window==='undefined')return null;const name=customName?.trim()||settings.address.trim()||`Смета от ${new Date().toLocaleDateString('ru-RU')}`;const fileName=`Smeta_${name.replace(/[<>:"/\\|?*\x00-\x1f]/g,'').replace(/\s+/g,'_').slice(0,60)||'Smeta'}_${new Date().toISOString().slice(0,10)}.html`;const url=URL.createObjectURL(new Blob([serializeEstimate(items,settings,name)],{type:'text/html;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download=fileName;document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);return fileName};
export const loadEstimateFromFile=async(file:File)=>{if(!file)throw new EstimateFileError('Файл не выбран');if(file.size>5*1024*1024)throw new EstimateFileError('Файл слишком большой (макс. 5 МБ).');const text=await file.text();const m=text.match(new RegExp(`<script[^>]*id=["']${SCRIPT_ID}["'][^>]*>([\\s\\S]*?)<\\/script>`,'i'));if(!m?.[1])throw new EstimateFileError('В файле нет данных сметы.');try{return parse(JSON.parse(m[1].replaceAll('<\\/script','</script').replaceAll('<\\!--','<!--')))}catch(e){if(e instanceof EstimateFileError)throw e;throw new EstimateFileError('Не удалось разобрать данные сметы.')}};
