'use client';
import * as React from 'react'; import * as DialogPrimitive from '@radix-ui/react-dialog'; import { X } from 'lucide-react'; import { cn } from '@/lib/utils';
export const Dialog=DialogPrimitive.Root; export const DialogTrigger=DialogPrimitive.Trigger; export const DialogClose=DialogPrimitive.Close; export const DialogPortal=DialogPrimitive.Portal;
export function DialogOverlay({className,...props}:React.ComponentProps<typeof DialogPrimitive.Overlay>){return <DialogPrimitive.Overlay className={cn('fixed inset-0 z-50 bg-black/50',className)} {...props}/>}
export function DialogContent({className,children,showCloseButton=true,...props}:React.ComponentProps<typeof DialogPrimitive.Content>&{showCloseButton?:boolean}){return <DialogPortal><DialogOverlay/><DialogPrimitive.Content className={cn('fixed left-1/2 top-1/2 z-50 w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 -translate-y-1/2 rounded-lg border bg-background p-6 shadow-lg',className)} {...props}>{children}{showCloseButton&&<DialogPrimitive.Close className="absolute right-4 top-4 opacity-70"><X className="h-4 w-4"/><span className="sr-only">Close</span></DialogPrimitive.Close>}</DialogPrimitive.Content></DialogPortal>}
export const DialogHeader=({className,...props}:React.ComponentProps<'div'>)=><div className={cn('flex flex-col gap-2 text-center sm:text-left',className)} {...props}/>;
export const DialogFooter=({className,...props}:React.ComponentProps<'div'>)=><div className={cn('flex flex-col-reverse gap-2 sm:flex-row sm:justify-end',className)} {...props}/>;
export const DialogTitle=({className,...props}:React.ComponentProps<typeof DialogPrimitive.Title>)=><DialogPrimitive.Title className={cn('text-lg font-semibold',className)} {...props}/>;
export const DialogDescription=({className,...props}:React.ComponentProps<typeof DialogPrimitive.Description>)=><DialogPrimitive.Description className={cn('text-muted-foreground text-sm',className)} {...props}/>;
